f():
	g++ main.c -std=c++11

debug:
	g++ main.c -std=c++11 -g

testRun:
	./a.out 3 3 1 1 1 test < testData
	./a.out 3 3 1 1 2 test < testData
	./a.out 3 3 1 1 3 test < testData
	./a.out 3 3 1 1 4 test < testData
