f():
	g++ main.c -g -std=c++11 -pthread

testRun:
	./a.out 3 3 1 1 1 test < testData
	./a.out 3 3 1 1 2 test < testData
	./a.out 3 3 1 1 3 test < testData
	./a.out 3 3 1 1 4 test < testData
	./a.out 3 3 1 1 5 test < testData
